2015/04/20 17:48:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/
---
2015/04/20 17:51:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:51:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:52:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/04/20 17:52:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:57:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=usuarios
---
2015/04/20 17:57:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:57:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:57:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:57:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/contact
---
2015/04/20 17:58:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:58:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuario
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/04/20 17:58:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuario
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/contact
---
2015/04/20 17:59:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuario
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuario
---
2015/04/20 17:59:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuario
---
2015/04/20 17:59:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 17:59:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 17:59:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 17:59:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=usuarios
---
2015/04/20 17:59:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:59:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:59:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 17:59:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 18:01:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php
---
2015/04/20 18:01:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 18:01:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 18:02:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/admin".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/admin')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 18:02:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/admin
---
2015/04/20 18:02:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/04/20 18:02:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/04/20 18:02:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/04/20 18:02:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=puertas
---
2015/04/20 18:02:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/04/20 18:02:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 18:03:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/04/20 18:03:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 18:18:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/04/20 18:18:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/04/20 18:18:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 18:18:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/usuario...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=puertas/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=puertas
---
2015/04/20 18:21:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuarios')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/04/20 18:21:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/04/20 18:21:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/04/20 18:21:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/04/20 18:24:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/index
---
2015/04/20 18:24:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/04/20 18:24:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/04/20 18:24:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/04/20 18:24:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/04/20 18:47:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/04/20 18:55:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=usuarios
---
2015/04/20 18:55:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=usuarios
---
2015/04/20 18:56:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=puertas
---
2015/04/20 19:11:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/contact
---
2015/04/20 19:11:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/contact
---
2015/04/20 19:11:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/04/20 19:11:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:28:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/login
---
2015/05/16 12:28:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 12:28:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:29:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=puertas
---
2015/05/16 12:29:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 12:48:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/index
---
2015/05/16 12:48:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 12:48:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/index
---
2015/05/16 12:48:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:48:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 12:48:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:48:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 12:49:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 12:49:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:49:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 12:49:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:49:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 12:49:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "puertas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('puertas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('puertas')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/puertas')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/puertas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:49:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 12:49:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:56:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/contact
---
2015/05/16 12:56:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 12:56:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 12:56:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:56:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 12:56:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('usuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('usuarios')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('Usuarios/usuari...')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=Usuarios/usuarios
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=user/regla
---
2015/05/16 12:56:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('user/regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=user/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=Usuarios/usuarios
---
2015/05/16 13:02:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 13:02:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/05/16 13:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/regla
---
2015/05/16 13:02:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/05/16 13:02:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/usuarios
---
2015/05/16 13:05:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 13:05:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "regla".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(270): CController->missingAction('regla')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('regla')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('site/regla')
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/proyecto/index.php?r=site/regla
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/16 13:57:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "susuarios".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('susuarios')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=susuarios
---
2015/05/19 11:00:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "reglas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('reglas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=reglas
---
2015/05/19 12:04:21 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=usuarios/index
---
2015/05/19 12:04:45 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=puertas/admin
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=puertas/create
---
2015/05/19 12:05:01 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('delete')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/delete')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=puertas/delete&id=1
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=puertas/view&id=1
---
2015/05/19 12:09:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "reglas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('reglas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=reglas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=site/puertas
---
2015/05/19 12:09:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "reglas".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('reglas')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=reglas
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=usuarios
---
2015/05/29 12:46:56 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`puertas`.`regla`, CONSTRAINT `regla_ibfk_1` FOREIGN KEY (`id_puertas`) REFERENCES `puertas` (`id_puertas`)). The SQL statement executed was: INSERT INTO `regla` (`id_usuarios`, `id_puertas`, `fecha_y_hora_entrada`, `fecha_y_hora_salida`) VALUES (:yp0, :yp1, :yp2, :yp3).
in C:\xampp\htdocs\proyecto\protected\controllers\ReglaController.php (73)
in C:\xampp\htdocs\proyecto\index.php (13)
2015/05/29 12:46:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`puertas`.`regla`, CONSTRAINT `regla_ibfk_1` FOREIGN KEY (`id_puertas`) REFERENCES `puertas` (`id_puertas`)). The SQL statement executed was: INSERT INTO `regla` (`id_usuarios`, `id_puertas`, `fecha_y_hora_entrada`, `fecha_y_hora_salida`) VALUES (:yp0, :yp1, :yp2, :yp3)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\proyecto\protected\controllers\ReglaController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): ReglaController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('regla/create')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=regla/create
HTTP_REFERER=http://localhost:8080/proyecto/index.php?r=regla/create
---
2015/05/29 13:02:50 [error] [php] Missing argument 3 for CHtml::listData(), called in C:\xampp\htdocs\proyecto\protected\views\regla\_form.php on line 25 and defined (C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\helpers\CHtml.php:2270)
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): ReglaController->renderInternal()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): ReglaController->renderFile()
#2 C:\xampp\htdocs\proyecto\protected\views\regla\create.php(18): ReglaController->renderPartial()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(126): require()
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): ReglaController->renderInternal()
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): ReglaController->renderFile()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(782): ReglaController->renderPartial()
#7 C:\xampp\htdocs\proyecto\protected\controllers\ReglaController.php(79): ReglaController->render()
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): ReglaController->actionCreate()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): ReglaController->runAction()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CAccessControlFilter->filter()
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): ReglaController->filterAccessControl()
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#15 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): ReglaController->runActionWithFilters()
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): ReglaController->run()
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController()
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#20 C:\xampp\htdocs\proyecto\index.php(13): CWebApplication->run()
REQUEST_URI=/proyecto/index.php?r=regla/create
in C:\xampp\htdocs\proyecto\protected\views\regla\_form.php (25)
in C:\xampp\htdocs\proyecto\protected\views\regla\create.php (18)
in C:\xampp\htdocs\proyecto\protected\controllers\ReglaController.php (79)
2015/07/28 17:36:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mostrar".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('mostrar')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=mostrar
---
2015/09/28 18:11:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mostrar".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('mostrar')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=mostrar
---
2015/09/28 18:11:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'puertas'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\proyecto\protected\views\usuarios\index.php(19): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\proyecto\protected\controllers\UsuariosController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): UsuariosController->actionIndex()
#22 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#32 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios
HTTP_REFERER=http://localhost/proyecto/index.php?r=site/login
---
2015/09/28 18:13:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'puertas'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\proyecto\protected\views\usuarios\index.php(19): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\proyecto\protected\controllers\UsuariosController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): UsuariosController->actionIndex()
#22 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios')
#32 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios
HTTP_REFERER=http://localhost/proyecto/index.php?r=site/login
---
2015/09/28 18:14:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'puertas'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\proyecto\protected\views\puertas\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\proyecto\protected\controllers\PuertasController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): PuertasController->actionIndex()
#22 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('')
#31 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas')
#32 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/proyecto/index.php?r=puertas
HTTP_REFERER=http://localhost/proyecto/index.php?r=site/login
---
2015/09/28 18:27:10 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('regla/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=regla/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=regla/index
---
2015/09/28 18:27:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('regla/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=regla/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=regla
---
2015/09/29 19:28:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mostrar".' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('mostrar')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=mostrar
---
2015/09/29 20:12:37 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=usuarios/create
---
2015/09/29 20:12:46 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=usuarios/create
---
2015/09/29 20:12:48 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('regla/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=regla/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=regla
---
2015/09/29 20:12:51 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=puertas/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas
---
2015/09/29 20:13:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=puertas/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas/index
---
2015/09/29 20:15:31 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('regla/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=regla/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=regla
---
2015/09/29 20:15:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=puertas/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas
---
2015/09/29 20:15:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/admin')
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios/admin
HTTP_REFERER=http://localhost/proyecto/index.php?r=usuarios
---
2015/09/30 11:17:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "controlador/admin"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php
HTTP_REFERER=http://localhost/proyecto/index.php?r=site/page&view=about
---
2015/09/30 11:17:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "controlador/admin"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas
---
2015/09/30 11:17:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "controlador/admin"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php
HTTP_REFERER=http://localhost/proyecto/index.php?r=site/page&view=about
---
2015/09/30 11:18:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "controlador/admin"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php
HTTP_REFERER=http://localhost/proyecto/index.php?r=site/login
---
2015/11/26 11:53:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "puertas_pendientes"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas_pendien...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=puertas_pendientes
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas/admin
---
2015/11/26 11:53:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "puertas_pendientes"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas_pendien...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=puertas_pendientes
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas
---
2015/11/26 11:54:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "puertas_pendientes"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas_pendien...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=puertas_pendientes
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas
---
2015/11/26 11:55:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "puertas_pendientes"' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas_pendien...')
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/proyecto/index.php?r=puertas_pendientes
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas
---
2016/02/03 19:44:00 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'id_puertas'. La sentencia SQL ejecutada fue: INSERT INTO `puertas_pendientes` (`id_puertas`) VALUES (:yp0).
in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php (73)
in C:\xampp\htdocs\proyecto\index.php (13)
2016/02/03 19:44:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'id_puertas'. The SQL statement executed was: INSERT INTO `puertas_pendientes` (`id_puertas`) VALUES (:yp0)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): PuertasPendientesController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/create
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/03 19:44:53 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'id_puertas'. La sentencia SQL ejecutada fue: INSERT INTO `puertas_pendientes` (`id_puertas`) VALUES (:yp0).
in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php (73)
in C:\xampp\htdocs\proyecto\index.php (13)
2016/02/03 19:44:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'id_puertas'. The SQL statement executed was: INSERT INTO `puertas_pendientes` (`id_puertas`) VALUES (:yp0)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): PuertasPendientesController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/create
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/10 16:18:35 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'id_puertas'. La sentencia SQL ejecutada fue: INSERT INTO `puertas_pendientes` (`id_puertas`) VALUES (:yp0).
in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php (73)
in C:\xampp\htdocs\proyecto\index.php (13)
2016/02/10 16:18:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5' for key 'id_puertas'. The SQL statement executed was: INSERT INTO `puertas_pendientes` (`id_puertas`) VALUES (:yp0)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(73): CActiveRecord->save()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): PuertasPendientesController->actionCreate()
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/create
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/20 18:26:52 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`puertas`.`regla`, CONSTRAINT `regla_ibfk_2` FOREIGN KEY (`id_usuarios`) REFERENCES `usuarios` (`id_usuarios`)). La sentencia SQL ejecutada fue: DELETE FROM `usuarios` WHERE `usuarios`.`id_usuarios`=15.
in C:\xampp\htdocs\proyecto\protected\controllers\UsuariosController.php (115)
in C:\xampp\htdocs\proyecto\index.php (13)
2016/02/20 18:26:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`puertas`.`regla`, CONSTRAINT `regla_ibfk_2` FOREIGN KEY (`id_usuarios`) REFERENCES `usuarios` (`id_usuarios`)). The SQL statement executed was: DELETE FROM `usuarios` WHERE `usuarios`.`id_usuarios`=15' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1807): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1227): CActiveRecord->deleteByPk('15')
#2 C:\xampp\htdocs\proyecto\protected\controllers\UsuariosController.php(115): CActiveRecord->delete()
#3 [internal function]: UsuariosController->actionDelete('15')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuariosController), Object(ReflectionMethod), Array)
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1116): CFilterChain->run()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('delete')
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#20 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/proyecto/index.php?ajax=usuarios-grid&id=15&r=usuarios%2Fdelete
HTTP_REFERER=http://localhost/proyecto/index.php?r=usuarios/admin
---
2016/02/20 18:28:38 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`puertas`.`regla`, CONSTRAINT `regla_ibfk_2` FOREIGN KEY (`id_usuarios`) REFERENCES `usuarios` (`id_usuarios`)). La sentencia SQL ejecutada fue: DELETE FROM `usuarios` WHERE `usuarios`.`id_usuarios`=15.
in C:\xampp\htdocs\proyecto\protected\controllers\UsuariosController.php (115)
in C:\xampp\htdocs\proyecto\index.php (13)
2016/02/20 18:28:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`puertas`.`regla`, CONSTRAINT `regla_ibfk_2` FOREIGN KEY (`id_usuarios`) REFERENCES `usuarios` (`id_usuarios`)). The SQL statement executed was: DELETE FROM `usuarios` WHERE `usuarios`.`id_usuarios`=15' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1807): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1227): CActiveRecord->deleteByPk('15')
#2 C:\xampp\htdocs\proyecto\protected\controllers\UsuariosController.php(115): CActiveRecord->delete()
#3 [internal function]: UsuariosController->actionDelete('15')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(UsuariosController), Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsuariosController), Object(ReflectionMethod), Array)
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1116): CFilterChain->run()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('delete')
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('usuarios/delete')
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#20 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/proyecto/index.php?r=usuarios/delete&id=15
HTTP_REFERER=http://localhost/proyecto/index.php?r=usuarios/view&id=15
---
2016/02/20 18:41:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php:157
Stack trace:
#0 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(55): PuertasPendientesController->loadModel('6')
#1 [internal function]: PuertasPendientesController->actionView('6')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PuertasPendientesController), Array)
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PuertasPendientesController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/view&id=6
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/20 18:41:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php:157
Stack trace:
#0 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(55): PuertasPendientesController->loadModel('6')
#1 [internal function]: PuertasPendientesController->actionView('6')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PuertasPendientesController), Array)
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PuertasPendientesController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/view&id=6
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/20 18:41:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php:157
Stack trace:
#0 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(55): PuertasPendientesController->loadModel('6')
#1 [internal function]: PuertasPendientesController->actionView('6')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PuertasPendientesController), Array)
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PuertasPendientesController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/view&id=6
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/20 18:41:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php:157
Stack trace:
#0 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(55): PuertasPendientesController->loadModel('6')
#1 [internal function]: PuertasPendientesController->actionView('6')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PuertasPendientesController), Array)
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PuertasPendientesController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/view&id=6
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/20 18:42:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php:157
Stack trace:
#0 C:\xampp\htdocs\proyecto\protected\controllers\PuertasPendientesController.php(55): PuertasPendientesController->loadModel('6')
#1 [internal function]: PuertasPendientesController->actionView('6')
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PuertasPendientesController), Array)
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PuertasPendientesController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertasPendient...')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/proyecto/index.php?r=puertasPendientes/view&id=6
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertasPendientes/create
---
2016/02/21 18:05:43 [error] [system.db.CDbCommand] CDbCommand::execute() falló: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`puertas`.`puertas_pendientes`, CONSTRAINT `puertas_pendientes_ibfk_1` FOREIGN KEY (`id_puertas`) REFERENCES `puertas` (`id_puertas`)). La sentencia SQL ejecutada fue: DELETE FROM `puertas` WHERE `puertas`.`id_puertas`=1.
in C:\xampp\htdocs\proyecto\protected\controllers\PuertasController.php (113)
in C:\xampp\htdocs\proyecto\index.php (13)
2016/02/21 18:05:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`puertas`.`puertas_pendientes`, CONSTRAINT `puertas_pendientes_ibfk_1` FOREIGN KEY (`id_puertas`) REFERENCES `puertas` (`id_puertas`)). The SQL statement executed was: DELETE FROM `puertas` WHERE `puertas`.`id_puertas`=1' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1807): CDbCommand->execute()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1227): CActiveRecord->deleteByPk('1')
#2 C:\xampp\htdocs\proyecto\protected\controllers\PuertasController.php(113): CActiveRecord->delete()
#3 [internal function]: PuertasController->actionDelete('1')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(PuertasController), Array)
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PuertasController), Object(ReflectionMethod), Array)
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1116): CFilterChain->run()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterPostOnly(Object(CFilterChain))
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('delete')
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('puertas/delete')
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#20 C:\xampp\htdocs\proyecto\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/proyecto/index.php?ajax=puertas-grid&id=1&r=puertas%2Fdelete
HTTP_REFERER=http://localhost/proyecto/index.php?r=puertas/admin
---
